### ISSUE TITLE
Make YAML template configurable

### ISSUE THREAD

**Issue by mxmehl** [scheibler/khard#146]
When adding a new contact, the full template (from [helpers.py#L263](https://github.com/scheibler/khard/blob/master/khard/helpers.py#L263)) is a bit too crowded for experienced users – I for myself don't need many of the fields.

Can we make this template configurable, either by a command line parameter or in khard.conf to use another plain yaml file? Right now the only way to edit this is by changing the helpers.py file before compilation which is not user-friendly.

**Comment by whnr** [comment]
For the time being, try this as a one liner in the terminal of your choice:

    tmp=$(mktemp tmp-vcard-XXXXXX.yaml); cp short.yaml $tmp; vim $tmp; khard add -i $tmp; rm $tmp

I made an alias out of it.

My `short.yaml` looks like this:
```yaml
First name : 
Last name  : 

Birthday : 

Organisation : 
Title : 

Phone :
    cell : 
    work : 
    home : 

Email :
    home : 
    work : 

Address :
    home :
        Extended : 
        Street   : 
        Code     : 
        City     : 
        Region   : 
        Country  : 

# notes
# for multi-line notes use:
#   Note : |
#       line one
#       line two
Note : 
````
