### ISSUE TITLE
feature: Represent private extension field in yaml for `details` / `modify`.

### ISSUE THREAD

**Issue by lucc** [scheibler/khard#51]
I have some vcards which hold data in "private extension fileds" (these fields all start with `X-`). I would like to view and edit these fields with `khard details` and `khard modify`.

For this I suggest that we add a new key to the top level dictionary of the yaml representation. Maybe "private extensions" or so (In the modify version there could also be a comment saying that these are the "X-..." fields in the vcard). As there should be no restriction on the number of repeated fields or type of field here, the best yaml representation might be a list of key: value pairs. The keys should represent the field names (with or without the X, I don't know) and the values should accept arbitrary data.

I image it to look something like this in the file created by `khard modify`:
```yaml
# ... first the normal stuff like before

# private extensions
# These fields are stored with a leading "X-" before the field name in the vcard files.
private_extensions:
  - SOME_KEY: some data
  - SOME_OTHER_KEY: 42
  - SOME_KEY: can be repeated, all occurrences will be stored in the vcard file
  - KEYS: |
      hold arbitrary
      data
```
